### ISSUE TITLE
Fails to generate PDF for "bash" man

### ISSUE THREAD

**Issue by delameter** [sebastiancarlos/manpdf#1]
Hello.
Generation fails when running:

```console
$ ./manpdf -o bash.pdf  --no-open-pdf bash 
Generating PDF for 'bash'
groff: can't find 'DESC' file
groff: fatal error: invalid device 'pdf'
```

System is Ubuntu 20.04.5 LTS 64-bit

```console
$ groff --version
GNU groff version 1.22.4

called subprograms:
GNU grops (groff) version 1.22.4
GNU troff (groff) version 1.22.4

$ bash --version
GNU bash, version 5.0.17(1)-release (x86_64-pc-linux-gnu)
```

**Comment by sebastiancarlos** [comment]
Thanks for the report. By default, Ubuntu comes with the `groff-base` package installed, which lacks PDF support. You can fix it by installing the `groff` package: `sudo apt install groff`.

Also, I noticed that Debian and other distros have compressed man pages by default, so I added optional gunzipping to the script. 

In short, you need to install groff (full version) and re-install manpdf.

Let me know if that works.

**Comment by sebastiancarlos** [comment]
Actually there's a way to make it work with `groff-base` too. I'll add that soon.

**Comment by sebastiancarlos** [comment]
This should work fine on the latest version. I'm closing this issue but feel free to reopen if there's any problem.

**Comment by delameter** [comment]
It works now, thank you :smiley:
